Add More Logging to get a better view of a rolling restart

diff --git a/templates/default/app-restart.sh.erb b/templates/default/app-restart.sh.erb
--- a/templates/default/app-restart.sh.erb
+++ b/templates/default/app-restart.sh.erb
@@ -40,10 +40,12 @@ function app_up {
 finish_requests
 
 # Restart the application
+echo "================ ATTEMPTING to RESTART <%= node[:hostname] %> ================"
 <%= @restart_command %>
 
 # Wait for the app to come back up or fail the restart
-app_up || die "restart failed"
+app_up || die "**************** RESTART FAILED <%= node[:hostname] %> ****************"
+echo "================ RESTART COMPLETE <%= node[:hostname] %> ================"
 
 # Add Instance back into the load balancer
 <%= "#{@bin_dir}/#{@add_bin}" %>
diff --git a/templates/default/rolling-restart.sh.erb b/templates/default/rolling-restart.sh.erb
--- a/templates/default/rolling-restart.sh.erb
+++ b/templates/default/rolling-restart.sh.erb
@@ -5,6 +5,10 @@ function die {
   exit 1
 }
 instances=(<%= @ip_addresses.join(' ') %>)
-for i in ${instances[@]}
-  do sudo -u <%= @user %> ssh <%= @user %>@$i <%= @app_restart_command %> || die "The app running on $i failed to restart"
+instance_num=1
+for i in ${instances[@]};do
+  echo "================ Starting Restart $instance_num of ${#instances[@]} ================"
+  sudo -u <%= @user %> ssh <%= @user %>@$i <%= @app_restart_command %> || die "**************** RESTART FAILED ON $i ****************"
+  echo "================ Finished Restart $instance_num of ${#instances[@]} ================"
+  ((instance_num++))
 done
